#pragma once

#include <SingleSoundInput.hpp>
#include <SoundNode.hpp>
#include <SoundChunk.hpp>

namespace flo {

    /**
     * SoundResult is a place where the sound stream generated by a
     * sound network can be accessed from outside - for example, to
     * play to the speakers, to write to a file, or for use by advanced
     * sound nodes which contain nested networks.
     */
    class SoundResult final : public SoundNode {
    public:
        SoundResult(SoundNetwork*);

        void getNextChunk(SoundChunk&);

        void reset();

        void setSource(SoundSource*) noexcept;

        SingleSoundInput& getInput() noexcept;
        const SingleSoundInput& getInput() const noexcept;

    private:
        SingleSoundInput m_input;

        void addStateFor(const SoundNode* node, const SoundState* state) override final;
        void removeStateFor(const SoundNode* node, const SoundState* state) override final;
        void resetStateFor(const SoundNode* node, const SoundState* state) override final;

        void onStateMoved(const SoundNode* node, const SoundState* from, const SoundState* to) override final;

    };

} // namespace flo
